// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBxcxjZVRB6k9wWWmhu_l1HxbmC5L96YQ',
    appId: '1:616515647688:web:810d5d69d00cf381d9cdfd',
    messagingSenderId: '616515647688',
    projectId: 'instagram-clone-3d4e7',
    authDomain: 'instagram-clone-3d4e7.firebaseapp.com',
    storageBucket: 'instagram-clone-3d4e7.appspot.com',
    measurementId: 'G-E9FXCRT78N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi29EUkRmjJhsdCO8MINqY4pcVEzVwM3M',
    appId: '1:616515647688:android:0a58698bd158cf7ed9cdfd',
    messagingSenderId: '616515647688',
    projectId: 'instagram-clone-3d4e7',
    storageBucket: 'instagram-clone-3d4e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSh1pmkFw9yoOgZ_U0CIbbC5hfA7TNm18',
    appId: '1:616515647688:ios:1642cd212fceb492d9cdfd',
    messagingSenderId: '616515647688',
    projectId: 'instagram-clone-3d4e7',
    storageBucket: 'instagram-clone-3d4e7.appspot.com',
    iosClientId: '616515647688-38k7aluval41878n0p7qh6sga1p1eo6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
