// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZmMgHzzTY1EtV3x1VughdGgl-bdYHrs',
    appId: '1:142316507733:web:7094288b8cfe23eab73adc',
    messagingSenderId: '142316507733',
    projectId: 'instagram-clone-32ca2',
    authDomain: 'instagram-clone-32ca2.firebaseapp.com',
    storageBucket: 'instagram-clone-32ca2.appspot.com',
    measurementId: 'G-DMXYY7FEEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7C2GSkMSrlrTReI_vdqYRY4tT5kI1XFU',
    appId: '1:142316507733:android:8dfa1bd9030c40fcb73adc',
    messagingSenderId: '142316507733',
    projectId: 'instagram-clone-32ca2',
    storageBucket: 'instagram-clone-32ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrkJ2i3ID0XWuTtRhxaWTKvti4sU5mZU',
    appId: '1:142316507733:ios:6b787d5898b870f4b73adc',
    messagingSenderId: '142316507733',
    projectId: 'instagram-clone-32ca2',
    storageBucket: 'instagram-clone-32ca2.appspot.com',
    iosClientId: '142316507733-ahkftsbidipjnqttlceat6momo62goal.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
